app/docs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, HiddenField
from wtforms.validators import DataRequired

PLACEHOLDERTEXT = "Click on the »Start Recording« button or press »Alt+S« and begin speaking. After your finished dictating, your text will be spellchecked and you can edit it to your liking."


class CreateForm(FlaskForm):
    title = StringField(
        'title',
        validators=[DataRequired()], 
        render_kw={
            "placeholder": "Insert your title", 
            'spellcheck': 'true'})
    body = TextAreaField(
        'body',
        render_kw={
            'spellcheck': 'true',
            'placeholder': PLACEHOLDERTEXT
        })
    dialect = HiddenField(default="en-US")


class UpdateForm(FlaskForm):
    title = StringField(
        'title',
        validators=[DataRequired()],
        render_kw={
            "placeholder": "Insert your title", 
            'spellcheck': 'true'})
    body = TextAreaField(
        'body',
        render_kw={
            'spellcheck': 'true',
            'placeholder': PLACEHOLDERTEXT
        })
    dialect = HiddenField(default="en-US")

app/docs/__init__.py
from flask import Blueprint

docs = Blueprint('docs', __name__)

from . import views

app/docs/views.py
from datetime import datetime

from flask import (flash, g, redirect, render_template, request,                      url_for)

from werkzeug.exceptions import abort

from app import db
from app.models import User, Doc, Replacement, dialects
from app.auth import login_required
from app.helpers import unsalt

from . import docs
from .forms import CreateForm, UpdateForm

@docs.route('/mydocs')
@login_required
def mydocs():
    docs = Doc.query.order_by(Doc.edited.desc()).filter_by(author_id=g.user.id)
    g.route = '/docs'
    return render_template('docs/index.html', docs=docs)

@docs.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    current_user = g.user
    form = CreateForm()
    replacements = get_replacements(current_user)
    if form.validate_on_submit():
        title = request.form['title']
        body = request.form['body']
        dialect = request.form['dialect']
        error = None

        if not title:
            error = 'A title is required.'

        if dialect not in dialects:
            dialect = current_user.prefered_dialect

        if error is not None:
            flash(error)
        else:
            new_post = Doc(
                title = title,
                body = body,
                author = current_user,
                dialect = dialect
            )
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('docs.mydocs'))
    form.dialect.data = current_user.prefered_dialect

    return render_template('docs/create.html', form=form, hash=unsalt(current_user.password), email=current_user.email, author_id=current_user.id, replacements=replacements)
    

@docs.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    current_user = g.user
    post = get_post(id)
    replacements = get_replacements(current_user)
    form = UpdateForm()
    if form.validate_on_submit():
        title = request.form['title']
        body = request.form['body']
        dialect = request.form['dialect']
        error = None

        if not title:
            error = 'A title is required.'

        if dialect not in dialects:
            dialect = post.dialect or current_user.prefered_dialect

        if error is not None:
            flash(error)
        else:
            post.title = title
            post.body = body
            post.dialect = dialect
            post.edited = datetime.utcnow()
            db.session.commit()
            return redirect(url_for('docs.mydocs'))
    form.title.data = post.title
    form.body.data = post.body
    form.dialect.data = post.dialect

    return render_template('docs/update.html', post=post, form=form, hash=unsalt(current_user.password), email=current_user.email, id=id,author_id=post.author_id, replacements=replacements)


@docs.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()
    flash("Entry deleted")
    return redirect(url_for('docs.mydocs'))


def get_post(id, check_author=True):
    """Helper function that returns the post for the given id,
    optionally it checks if the post-author is the current user."""
    current_user = g.user
    post = Doc.query.filter_by(id=id).first()

    if post is None:
        abort(404, "Doc id {0} doesn't exist.".format(id))

    if check_author and post.author != current_user:
        abort(403)

    return post

def get_replacements(user):
    """Helper function that returns the replacements of the given user."""
    replacements_query = Replacement.query.filter_by(author_id=user.id).order_by().all()
    replacements = []
    for entry in replacements_query:
        replacements.append([entry.id, entry.placeholder, entry.substitute])
    return replacements

app/templates/docs/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link
            rel="preload"
            href="{{ url_for('static', filename='cdn/tinymce/skins/lightgray/fonts/tinymce.woff') }}"
            as="font"
            crossorigin
        />
        <link
            rel="preload"
            href="{{ url_for('static', filename='cdn/tinymce/skins/lightgray/skin.min.css') }}"
            as="style"
        />
        <link
            rel="preload"
            href="https://code.jquery.com/jquery-3.1.1.min.js"
            as="script"
        />
        <link
            rel="preload"
            href="{{ url_for('static', filename='cdn/semantic/semantic.min.js') }}"
            as="script"
        />
        <link
            rel="preload"
            href="{{ url_for('static', filename='cdn/tinymce/tinymce.min.js') }}" as="script"
        />
        <link
            rel="preload"
            href="{{ url_for('static', filename='js/webspeech/main.js') }}"
            as="script"
            crossorigin
        />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}Dictandu{% endblock %}</title>
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='cdn/semantic/semantic.min.css') }}"
        />
        <style>
            :root {
                --base_color: white;
                --base_bg_color: #f5f6f7;
                --text_color: #3b3e45;
                --selected_fg_color: white;
                --selected_bg_color: #5294e2;
                --button_primary_color: #5a96ec;
                --primary_color: #5a96ec;
                --link_color: #2679db;
                --link_visited_color: #1e61b0;
                --warning_color: #f27835;
                --error_color: #fc4138;
                --warning_fg_color: white;
                --error_fg_color: white;
                --success_color: #73d216;
                --destructive_color: #f04a50;
                --suggested_color: #4dadd4;
                --destructive_fg_color: white;
                --suggested_fg_color: white;
                --sidebar_bg: #353945;
                --sidebar_fg: #bac3cf;
                --sidebar_border: var(--sidebar_bg);
                --light_bg_color: #e9eaed;
                --dark_bg_color: #404552;
            }
            .Notification.ui.one.column.stackable.center.aligned.page.grid {
                position: fixed;
                left: 0;
                top: 0;
                z-index: 100000;
                width: 100%;
                padding-top: 0;
            }
            .fixed.menu > .container {
                margin-left: 0;
                margin-right: 0;
                width: 100%;
                max-width: none;
            }
            .sidebar.ui.menu .item {
                padding-left: 2em;
                padding-right: 2em;
            }
            .ui.inverted.menu {
                background: var(--sidebar_bg);
            }
            .ui.inverted.menu .active.item {
                background: var(--selected_bg_color);
            }
            .ui.primary.button,
            .ui.primary.buttons .button {
                background-color: var(--button_primary_color);
            }
            @media only screen and (min-width: 1145px) {
                .fixed.main.menu {
                    display: none;
                }
                .ui.vertical.inverted.sidebar.menu.left.borderless {
                    visibility: visible;
                    -webkit-transform: translate3d(0, 0, 0);
                    transform: translate3d(0, 0, 0);
                }
                .pusher {
                    -webkit-transform: translate3d(260px, 0, 0);
                    transform: translate3d(260px, 0, 0);
                }
                .ui.container {
                    width: calc(100% - 290px);
                    margin-left: 0 !important;
                    padding-left: 2em;
                }
            }
        </style>
        {% block style %}{% endblock %}
        <!-- Matomo -->
        <script type="text/javascript">
            var _paq = _paq || [];
            /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
            _paq.push(['setCookieDomain', '*.www.dictandu.com']);
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
                var u = '//vollernter.org/';
                _paq.push(['setTrackerUrl', u + 'piwik.php']);
                _paq.push(['setSiteId', '6']);
                var d = document,
                    g = d.createElement('script'),
                    s = d.getElementsByTagName('script')[0];
                g.type = 'text/javascript';
                g.async = true;
                g.defer = true;
                g.src = u + 'piwik.js';
                s.parentNode.insertBefore(g, s);
            })();
        </script>
        <!-- End Matomo Code -->
    </head>
    <body class="minimal pushable" style="height: 100vh;">
        {% for message in get_flashed_messages() %}
        <div
            class="Notification ui one column stackable center aligned page grid"
        >
            <div class="column twelve wide">
                <div class="ui bottom attached compact info message">
                    <i class="close icon"></i>
                    <p>{{ message }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        <div
            class="ui vertical inverted sidebar menu left borderless"
            style="display:flex; padding-top: 5em; padding-bottom: 1em;"
        >
            <div class="item">
                <a
                    class="ui logo icon image"
                    href="{{ url_for('docs.mydocs') }}"
                >
                    <img
                        src="{{ url_for('static', filename='img/logo.svg') }}"
                        style="height: 2em;"
                        alt="Logo"
                    />
                </a>
            </div>
            <a
                class="{% if g.route == '/docs'%}active{% endif %} item"
                href="{{ url_for('docs.mydocs') }}"
            >
                <i class="file alternate outline icon"></i> My Documents
            </a>
            <a class="item" href="{{ url_for('auth.logout') }}">
                <i class="power off icon"></i> Logout
                <small>{{ current_user.username.split(" ")[0] }}</small>
            </a>
            <a
                class="right item"
                style="margin-top:auto;"
                href="{{ url_for('pages.help') }}"
                target="blank"
            >
                <i class="question circle outline icon"></i> Help
            </a>
            <a
                class="right item"
                href="https://bitbucket.org/marco_rockiger/dictateio/issues/new"
                target="blank"
            >
                <i class="bug icon"></i> Report Error / Ask question
            </a>
        </div>
        <div class="ui fixed inverted main menu" style="height: 3em;">
            <div class="ui container">
                <a class="launch icon item"> <i class="content icon"></i> </a>

                <div class="item">{% block header %}Dictandu{% endblock %}</div>
            </div>
        </div>
        <div class="pusher">
            <!-- Site content ! -->
            {% block content %}{% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="{{ url_for('static', filename='cdn/semantic/semantic.min.js') }}"></script>
        <script>
            $('.launch.icon.item').click(() => {
                $('.ui.sidebar').sidebar('toggle');
            });

            $('.message .close').on('click', function() {
                $(this)
                    .closest('.message')
                    .transition('fade');
            });
        </script>
        {% block script %}{% endblock %}
    </body>
</html>

app/templates/docs/create.html
{% extends 'docs/create_update_style.html' %}

{% block header %}New Document{% endblock %}

app/templates/docs/create_update.html
{% extends 'docs/base.html' %}

{% block content %}

<main class="ui container">
<div style="display:none;" id="credentials" data-email="{{ email }}" data-hash="{{ hash }}" data-author_id="{{ author_id }}" data-id="{% if id is defined %}{{ id }}{% endif %}"></div>
<div style="display:none" id="replacements" data-replacements="{{ replacements }}"></div>

<form method="post" id="docform">
    <div class="ui equal width grid">
            <div id="leftside" class="column my-leftside">
                <div class="ui top attached menu">
                    <div class="right menu">
                        <div class="ui icon item horizontally fitted borderless">
                            <i id="info_button" class="info circle circular grey link icon" style="opacity: 0.7;" title="Show Info"></i>
                        </div>
                        <div class="ui icon item borderless">
                            <i id="settings_button" class="sun outline circular grey link icon" style="opacity: 0.7;" title="Change settings"></i>
                        </div>
                        <div class="ui icon item horizontally fitted borderless">
                            <i id="export_button" class="cloud download circular grey link icon" style="opacity: 0.6;" title="Export as HTML"></i>
                        </div>
                        <div class="ui icon item right borderless">
                            <button id="submit" type="submit" class="ui primary button">
                                <!-- <i class="save icon"></i> -->
                                Save
                            </button>
                        </div>
                        <div id="switch-right" class="ui link icon item right my-switch" title="Switch sides" center">
                            <i class="caret square right outline link icon"></i>
                        </div>
                    </div>
                </div> <!-- End Menu -->

                <div id="leftside-wrapper" class="ui bottom attached segment my-leftside-wrapper">

                    <div class="ui fluid transparent input dividing">
                        <label class="my-leftside-label" for="title">title</label>
                    </div>
                    <div class="ui fluid transparent input dividing">
                        <input id="title" name="title" placeholder="Insert your title" title="Insert your title" required="" spellcheck="true" type="text" value="{% block title %}{% endblock %}" />
                    </div>

                    <!-- Automatic substitution -->
                    <div class="my-leftside-label">Automatic substitution <i class="question circle outline link icon my-help-popup" data-variation="very wide" data-html="<h3>Automatic Substitution</h3><p>Automatic substitution enables you to replace words, that are notoriously difficult for speech recognition, with placeholder words. For example, speech recognition doesn&#39;t know company names from and small companies.</p>
                        <p>Let&#39;s say you would like to use <strong>Dictandu</strong> in your document. You could use the word <strong>John</strong> as a placeholder for Dictandu. Enter <strong>John</strong> on the left side under the <strong>Replace</strong> column and enter <strong>Dictandu</strong> on the right site under the <strong>With</strong> Column.</p>
                        <p>Now the next time you will dictate the word <strong>John</strong>, <strong>Dictandu</strong> will automatically be inserted in your document.</p>"></i></div>
                    <div id="automatic-substitution" class="ui secondary segment">
                        <div class="ui form my-substitution__row ">
                            <div class="inline fields my-substition__row__label">
                            <div class="one wide field" style="width: 2.25rem !important;">
                                    <div class="ui checkbox" style="visibility:hidden;">
                                        <input type="checkbox">
                                        <label></label>
                                    </div>
                            </div>
                            <div class="seven wide field">
                                <label>Replace</label>
                            </div>
                            <div class="seven wide field">
                                <label>With</label>
                            </div>
                            <div class="one wide field">
                            </div>
                            </div>
                        </div>
                        <div id="automatic-substitution-row" class="ui form my-substitution__row">
                            <div class="inline fields">
                                <div class="one wide field" style="width: 1.75rem !important;">
                                    <div class="ui mini checkbox" style="visibility:hidden;">
                                        <input type="checkbox">
                                        <label></label>
                                    </div>
                                </div>
                                <div class="seven wide field">
                                <input id="placeholder" type="text" placeholder="Phrase to replace" title="Phrase to replace">
                                </div>
                                <div class="seven wide field">
                                <input id="substitution" type="text" placeholder="Replacement" title="Replacement">
                                </div>
                                <div class="one wide field">
                                    <i class="close icon"  style="visibility:hidden;"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END Automatic substitution -->


                    <!-- <aside id="contexthelp" class="ui secondary segment">
                        <div id="reviewhelp">
                            <h2 class="ui header">You are in Review Mode</h2>
                            <p>Click on <b>Start Recording</b> to dictate. The editor will switch into dictation mode.</p>
                        </div>
                        <div id="dictatehelp" style="display:none">
                                <h2 class="ui header">You are in Dictation Mode</h2>
                                <p>Click on <b>Stop Recording</b> to stop dictating. The editor will switch back into review mode.</p>
                        </div>
                        <h2 class="ui header">How does Dictandu work?</h2>
                        <p>Dictandu's editor has two modes: <b>Dictation</b> and <b>Reviewing</b>.</p>
                        <p>You get the most out of Dictandu with the following workflow:</p>
                        <ul>
                            <li>Dictate</li>
                            <li>Review and Edit</li>
                            <li><b>Repeat!</b></li>
                        </ul>
                        <p>While you are dictating don't think about errors or structure. Just let your mouth moving and your words flow!</p>
                        <p>After you have dictated your first draft, switch into editing mode, structure your text, revise your work, check for style and spelling errors.</p>
                        <p>Repeat this two-step process until you finish your piece.</p>

                    </aside> -->
                </div>


            </div> <!-- END Leftside -->
            <div id="rightside" class="column my-rightside">
                {{ form.hidden_tag()}}
                {{ form.body(style="display: none;") }}
                <div class="ui segments">
                    <div id="editor" class="ui segment"></div>
                    <div class="ui segment footer">
                        <div id="interim_wrapper" class="interim_wrapper hidden">
                            <div id="interim_label" class="interim_label"><b>Interim Result:</b></div>
                            <div id="interim_span" class="interim"></div>
                        </div>
                    </div>
                </div>

                <!-- Start Button Menu -->
                <div class="ui menu" style="position: absolute;top: 1em;right: 0px;z-index: 100;margin-top: calc(0.5em);border: none;box-shadow: none;height: 3.8em;border-radius: 0;border-bottom: 1px solid silver;margin: 0;">
                    <div class="ui icon item right borderless">
                        <div id="start_button" class="ui green button" title="Alt+S">Start Recording</div>
                    </div>
                    <div id="switch-left" class="ui link icon item right my-switch" title="Switch left" center">
                        <i class="caret square left outline link icon"></i>
                    </div>
                </div> <!-- End Start Button Menu -->

            </div> <!-- End rightside -->
        </div>
</form>
</main>

<div id="settings_popup" class="ui mini modal">
    <div class="header">
        Coose Language
    </div>
    <div class="content">
        <form  class="ui equal width form" id="div_language">
        <div class="fields">
            <div class="field">
                <select id="select_language"></select>
            </div>
            <div class="field">
                <select id="select_dialect"></select>
            </div>
        </div>
    </form>
    </div>
    <div class="actions">
        <div class="ui ok primary right icon button">
        Close
        </div>
    </div>
</div>

<div id="export_popup" class="ui modal">
    <div class="header">
        Export as HTML
    </div>
    <div class="content">
        <div class="ui form">
            <div class="field">
                <textarea spellcheck="false" name="export_textarea"
                id="export_textarea" style="height: 76vh; max-height: 76vh;"></textarea>
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui ok primary right icon button">
        Close
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

<script>
function switchSide() {
        $('#rightside').transition({
            animation: 'fly left',
            duration: '1s'
        });
    }
$('#switch-right').click(switchSide);
$('#switch-left').click(switchSide);

$('.my-help-popup').popup();
</script>

<!-- <script src="{{ url_for('static', filename='cdn/prosemirror.js') }}"></script>
<script src="{{ url_for('static', filename='cdn/markdown-it.js') }}"></script>
<script src="{{ url_for('static', filename='cdn/prosemirror-markdown.js') }}"></script>
<script src="{{ url_for('static', filename='cdn/beyond-grammar-plugin.js') }}"></script> -->
<script src="{{ url_for('static', filename='cdn/tinymce/tinymce.min.js') }}"></script>
<script src="{{ url_for('static', filename='cdn/tinymce-placeholder.min.js') }}"></script>
<!-- <script src="{{ url_for('static', filename='js/webspeech/tinymce-dictandu-plugin/tinymce-dictandu.plugin.js') }}"></script> -->
<!-- <script src="https://prowriting.azureedge.net/beyondgrammar-tinymce/1.0.22/dist/beyond-grammar-plugin.js"></script> -->

<script type="module" src="{{ url_for('static', filename='js/webspeech/main.js') }}"></script>
<script src="{{ url_for('static', filename='cdn/marked.min.js') }}"></script>
{% endblock %}

app/templates/docs/index.html
{% extends 'docs/base.html' %}
{% block header %}My Documents{% endblock %}
{% block style %}
<style>
.pusher {padding-top: 5em; padding-bottom: 2em; display: flex;}
@media only screen and (min-width: 1145px) {
    .pusher {
    padding-top: 2em;
    }
}

.ui.card, .ui.cards>.card {
    width: 220px;
    height: 240px;
    max-height: 100%;
    overflow: hidden;
}
.ui.card>.content .trash.icon:hover, .ui.cards>.card>.content .trash.icon:hover {
opacity: 1;
color: #ff2733;
}
@media only screen and (min-width: 520px) {
    .ui.centered.cards {
        -webkit-box-pack: start;
        -ms-flex-pack: start;
        justify-content: start;
    }
}

.mydocs__onboarding {
    margin-left: 0;
    margin-top: 1em;
    max-width: 455px;
}

.alert {
    padding: 1rem 2rem;
    border-radius: 5px;
}

.alert_secondary {
    background: #eee;
}
.mydocs__onboarding .alert {
    display: flex;
}
.mydocs__onboarding__arrow-container__arrow {
    max-width: 6rem;
    width: 100%;
    margin-right: 1rem;
}
</style>
{% endblock %}

{% block script %}
<script>
$('.delete .link').click( function (event) {
    event.preventDefault();
    event.stopPropagation(); 
    console.log($(this).closest('input'));
    $(this).next('input').click();
    return 
});
</script>
{% endblock %}

{% block content %}
<main class="ui container">
  <div class="ui centered cards">
      <a href="{{ url_for('docs.create') }}" class="ui card">
          <div class="content">
              <main style="padding-top: 35px; color: rgba(0,0,0,0.4);" class="center aligned description">
                  <i class="huge file outline icon"></i>
                  <h2 class="huge header">New</h2>
              </main>
          </div>
      </a>
      {% for post in docs %}
      <a class="ui card" href="{{ url_for('docs.update', id=post.id) }}">
          <div class="content">
              <header class="header">{{ post.title }}</header>
              <!-- <div class="meta">
                <span>{{ post.created.strftime('%Y-%m-%d') }}</span>
              </div> -->
              <main class="description">
              <p>{{ post.body[0:100] }}</p>
              </main>
          </div>
          <div class="extra content">
              <form class="delete" action="{{ url_for('docs.delete', id=post['id']) }}" method="post">
                  <span class="right floated link">
                      <i class="large trash alternate outline icon"></i>
                  </span>
                  <input style="display: none;" type="submit" value="" onclick="return confirm('Do you really want to delete »{{ post.title }}«?');">
              </form>
          </div>
      </a>
      {% endfor %}
      
  </div>
  {% if docs.count() < 5 %}
    <div class="mydocs__onboarding">
        <div class="alert alert_secondary">
            <div class="mydocs__onboarding__arrow-container">
                <img class="mydocs__onboarding__arrow-container__arrow" src="{{ url_for('static', filename='img/arrow-right-curve.svg') }}" alt="" />
            </div>
            <div>
                <h3>Let's dictate a new post!</h3>
                <p>
                    A smarter way to create your blog post awaits you right there...
                </p>
                <p>
                    Alternatively, you can <b>checkout</b> the <b>Example Project</b>.
                </p>
            </div>
        </div>
    </div>
    {% endif %}
</main>
{% endblock %}

app/templates/docs/update.html
{% extends 'docs/create_update_style.html' %}

{% block header %}{{ post['title'] }}{% endblock %}
{% block title %}{{ post.title }}{% endblock %}